import { Inter } from 'next/font/google'
import './globals.css'
import Context from './context/context'
import ContextProvider from './context/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stopwatch',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextProvider>
      <body className={inter.className}>{children}</body>
      </ContextProvider>
    </html>
  )
}
